version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_6stk42
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - php-fpm
    networks:
      - app-network
    restart: unless-stopped

  php-fpm:
    build:
      context: ./docker/php
    image: php:8.2-fpm-alpine
    container_name: fpm_6stk42
    volumes:
      - ./:/app
    env_file:
      - .env
    networks:
      - app-network
    restart: unless-stopped

  mysql:
    image: mysql:5.7.16
    restart: always
    container_name: mysql_6stk42
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=my_base
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
    volumes:
      - ./data/mysql:/var/lib/mysql/
      - ./:/app
      - ./docker/mysql-logs:/app/logs/mysql/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
  session:
    driver: local
