version: '3.8'

# Использование: docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d

services:
  nginx:
    volumes:
      - ./:/app
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - node

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: node_6stk42
    restart: unless-stopped
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - ./public/uploads:/app/public/uploads
    ports:
      - "5173:5173"
    networks:
      - app-network
